### Register
POST http://localhost:7074/api/auth/register
Content-Type: application/json

{
  "username": "user6",
  "password": "p1234"
}

### Login user
POST http://localhost:7074/api/auth/login
Content-Type: application/json

{
  "username": "user6",
  "password": "p1234"
}
> {%
    client.global.set("token", response.body.token);
%}

### Login admin
POST http://localhost:7074/api/auth/login
Content-Type: application/json

{
    "username": "{{ADMIN_NAME}}",
    "password": "{{ADMIN_PASSWORD}}"
}
> {%
    client.global.set("admin-token", response.body.token);
%}

### Admin add new movie, given token belongs to admin
POST http://localhost:7074/movies/add
Accept: application/json
Authorization: {{admin-token}}

### Get all movies request
GET http://localhost:7074/api/movies
Accept: application/json

### Save movie data from GET response
GET http://localhost:7074/api/movies/1
Accept: application/json

> {%
    client.global.set("movie", JSON.stringify(response.body));
%}

### Use saved movie data in POST request
POST http://localhost:7074/movies/like/1
Content-Type: application/json

{{movie}}

### Get a list of recommended movies from user with given token
GET http://localhost:7074/api/movies/recommend
Accept: application/json
Authorization: Bearer {{token}}

### Get a list of movies with a given genre (Science Fiction)
GET http://localhost:7074/api/movies/science-fiction
Accept: application/json

### Get a list of movies with a given genre (Comedy)
GET http://localhost:7074/api/movies/comedy
Accept: application/json

### Get a list of liked movies from a user with a given token
GET http://localhost:7074/api/movies/history
Accept: application/json
Authorization: {{token}}

### Test if given token is valid
GET http://localhost:7074/api/secured/demo
Authorization: Bearer {{token}}
